name: Deploy AWS VPC

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: opentofu/setup-opentofu@v1.0.3
      - name: OpenTofu Setup and Validate
        run: |
          cd ./IaC/
          sh init_and_validate.sh ./aws/templates/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_INFRA_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_INFRA_KEY }}
