name: Run Cypress

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: build cypress
        run: |
          cd ./test/cypress
          yarn

      - name: run test
        run: |
          cd ./test/cypress
          yarn cypress run
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: cypress_test_results
          path: ./test/cypress/mochawesome-report
          retention-days: 1
          overwrite: true
