name: Run Cypress

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: build cypress
        run: |
          cd ./test/cypress
          yarn

      - name: run test
        run: |
          cd ./test/cypress
          yarn cypress run --reporter mochawesome

      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: "./test/cypress/mochawesome-report/mochawesome.html"
